### ISSUE TITLE
Consider using autoprefixer rather than mixins with hardcoded vendor prefixes

### ISSUE THREAD

**Issue by toddmilliken** [bu-ist/responsive-foundation#204]
I think we can optimize our compiled CSS files by using autoprefixer to add in the vendor prefixes to the resulting CSS files, aka a Post CSS transform.

## What is Autoprefixer?
Autoprefixer is a Post CSS package that takes an input CSS file and a browserslist config, and pings the [caniuse.com](https://caniuse.com/) API, and adds vendor prefixes/browser-specific rules based on our browserslist config.

## How do we add Autoprefixer to our workflow?

The following packages will need to be installed:

- [grunt-postcss](https://github.com/nDmitry/grunt-postcss)
- [autoprefixer](https://github.com/postcss/autoprefixer)

Then we can add a grunt 'postcss' task that will add prefixes where necessary, based on the [browserslist config already in our `package.json`](https://github.com/bu-ist/responsive-foundation/blob/7966bf5116190ea1d85bf62b564f10816b36376b/package.json#L27-L31).. Read more on [browserslist here](https://github.com/browserslist/browserslist).

## Benefits of Autoprefixer

- Reduce the need for many of Foundation's mixins outlined here: https://github.com/bu-ist/responsive-foundation/blob/7966bf5116190ea1d85bf62b564f10816b36376b/css-dev/burf-base/_mixins.scss#L40-L460
- Removes the maintainability burden of updating vendor prefixes/removing unneeded ones.
- Smaller file sizes due to the removal of unneeded vendor prefixes (ie6-9, old iOS, moz, and webkit prefixes).
- Prepares us for a vendor-prefix-free world that awaits us in the future. See the [Vendor Prefixes article on the MDN Docs](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix)
>Browser vendors are working to stop using vendor prefixes for experimental features.

**Comment by ashleykolodziej** [comment]
This is a great idea! Let's explore it.

**Comment by toddmilliken** [comment]
This is complete!
