### ISSUE TITLE
Chrome dev tools lose of inspection sticky elements

### ISSUE THREAD

**Issue by saucyrooster** [bu-ist/responsive-foundation#212]
Since the release of Responsive 2.0.

Chrome dev tools looses element upon refresh.

Expected
Select an element on the page in Chrome dev tools for inspection and the element becomes highlighted for inspection tests or additional styling. When you refresh the page you would loose the styling but the element was sticky for quick relocation.

Currently
Upon refresh element is no longer highlighted or selected. In responsive-foundation 1.0 this function currently still works

I suspect this is a mapping related issue.

**Comment by ashleykolodziej** [comment]
This needs further review to figure out what we can do about this.
