### ISSUE TITLE
Skip Link mixin or @extend? 

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-foundation#214]
In r-editorial we did not use navigation.scss since all our nav was custom. However, the skip link styles are useful and had to be duplicated. Should the skip link move to a different file... maybe an Accessibility.scss partial? or make it a mixin so the base styles for the skip link don't have to be recreated?

**Comment by ashleykolodziej** [comment]
I like this idea - we have an existing accessibility partial here: https://github.com/bu-ist/responsive-foundation/blob/develop/css-dev/burf-base/_accessibility.scss

And I think adding a mixin there that we call from the navigation partial is a good idea. Nice catch!
